#!/bin/bash
# Setup script for local worker
# Run this after Terraform has been applied to configure your local environment

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Agent Grid - Local Worker Setup${NC}"
echo "================================="
echo ""

# Check if terraform outputs are available
if ! command -v terraform &> /dev/null; then
    echo -e "${RED}Error: terraform not found. Please install Terraform.${NC}"
    exit 1
fi

# Get the terraform directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TF_DIR="$SCRIPT_DIR/../infrastructure/terraform/environments/dev"

if [ ! -d "$TF_DIR" ]; then
    echo -e "${RED}Error: Terraform directory not found at $TF_DIR${NC}"
    exit 1
fi

echo "Fetching configuration from Terraform outputs..."
cd "$TF_DIR"

# Get outputs
JOBS_QUEUE_URL=$(terraform output -raw jobs_queue_url 2>/dev/null || echo "")
RESULTS_QUEUE_URL=$(terraform output -raw results_queue_url 2>/dev/null || echo "")
AWS_ACCESS_KEY=$(terraform output -raw worker_access_key_id 2>/dev/null || echo "")
AWS_SECRET_KEY=$(terraform output -raw worker_secret_access_key 2>/dev/null || echo "")

if [ -z "$JOBS_QUEUE_URL" ]; then
    echo -e "${RED}Error: Could not get Terraform outputs. Have you run 'terraform apply'?${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}Configuration retrieved successfully!${NC}"
echo ""

# Create AWS profile
AWS_PROFILE_NAME="agent-grid-worker"
AWS_CONFIG_DIR="$HOME/.aws"

mkdir -p "$AWS_CONFIG_DIR"

echo "Creating AWS profile: $AWS_PROFILE_NAME"

# Check if profile already exists
if grep -q "\[$AWS_PROFILE_NAME\]" "$AWS_CONFIG_DIR/credentials" 2>/dev/null; then
    echo -e "${YELLOW}Warning: Profile $AWS_PROFILE_NAME already exists. Updating...${NC}"
    # Remove existing profile section (simple approach)
    sed -i.bak "/\[$AWS_PROFILE_NAME\]/,/^\[/d" "$AWS_CONFIG_DIR/credentials" 2>/dev/null || true
fi

# Add credentials
cat >> "$AWS_CONFIG_DIR/credentials" << EOF

[$AWS_PROFILE_NAME]
aws_access_key_id = $AWS_ACCESS_KEY
aws_secret_access_key = $AWS_SECRET_KEY
EOF

echo "AWS credentials saved to ~/.aws/credentials"

# Create .env file for local development
cd "$SCRIPT_DIR/.."
ENV_FILE=".env.worker"

cat > "$ENV_FILE" << EOF
# Agent Grid Worker Configuration
# Generated by setup-local-worker.sh

# AWS/SQS Configuration
AGENT_GRID_AWS_REGION=us-west-2
AGENT_GRID_SQS_JOB_QUEUE_URL=$JOBS_QUEUE_URL
AGENT_GRID_SQS_RESULT_QUEUE_URL=$RESULTS_QUEUE_URL

# Use AWS profile for credentials
AWS_PROFILE=$AWS_PROFILE_NAME

# Worker settings
AGENT_GRID_DEPLOYMENT_MODE=worker

# Add your API keys below:
# ANTHROPIC_API_KEY=sk-ant-...
# GITHUB_TOKEN=ghp_...
EOF

echo "Environment file created: $ENV_FILE"

echo ""
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo "To run the local worker:"
echo ""
echo "  1. Add your API keys to $ENV_FILE:"
echo "     - ANTHROPIC_API_KEY"
echo "     - GITHUB_TOKEN (if using GitHub issues)"
echo ""
echo "  2. Start the worker:"
echo "     source $ENV_FILE && poetry run python -m agent_grid.worker"
echo ""
echo "  Or use the convenience alias:"
echo "     ./scripts/run-worker.sh"
echo ""
