"""Phase 3 (COMPLEX path): Decompose complex issues into sub-tasks.

Calls Claude to generate an implementation plan, then creates
sub-issues in GitHub with dependency tracking.
"""

import json
import logging

import anthropic

from ..config import settings
from ..issue_tracker import get_issue_tracker
from ..issue_tracker.label_manager import get_label_manager
from ..issue_tracker.metadata import embed_metadata

logger = logging.getLogger("agent_grid.planner")


PLANNING_PROMPT = """You are a senior tech lead planning work decomposition.

Parent Issue #{issue_number}: {title}

{body}

Create an implementation plan:
1. Break this into the smallest possible independent sub-tasks
2. Each sub-task should be completable in a single PR (< 200 lines)
3. Identify dependencies between sub-tasks (what blocks what)
4. Order sub-tasks by dependency (leaves first)
5. Maximum {max_sub_issues} sub-tasks

Output as JSON:
{{
  "plan_summary": "Brief summary of the approach",
  "sub_tasks": [
    {{
      "title": "Short descriptive title",
      "description": "What to implement and why",
      "acceptance_criteria": ["Testable criterion 1", "Testable criterion 2"],
      "depends_on": [],
      "estimated_files": ["path/to/file.py"],
      "complexity": 1-5
    }}
  ],
  "risks": ["Potential risk 1"]
}}

Respond ONLY with the JSON object, no markdown fences."""


class Planner:
    """Decomposes complex issues into sub-tasks."""

    def __init__(self):
        self._client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
        self._tracker = get_issue_tracker()
        self._labels = get_label_manager()

    async def decompose(self, repo: str, issue_number: int, title: str, body: str) -> list[dict]:
        """Decompose a complex issue into sub-issues.

        Args:
            repo: Repository in owner/name format.
            issue_number: Parent issue number.
            title: Parent issue title.
            body: Parent issue body.

        Returns:
            List of created sub-issue dicts with number and title.
        """
        # Label as planning
        await self._labels.transition_to(repo, str(issue_number), "ai-planning")

        prompt = PLANNING_PROMPT.format(
            issue_number=issue_number,
            title=title,
            body=body or "(no description)",
            max_sub_issues=10,
        )

        try:
            response = await self._client.messages.create(
                model=settings.planning_model,
                max_tokens=4096,
                messages=[{"role": "user", "content": prompt}],
            )
            text = response.content[0].text.strip()
            plan = json.loads(text)
        except Exception as e:
            logger.error(f"Planning failed for issue #{issue_number}: {e}")
            await self._labels.transition_to(repo, str(issue_number), "ai-failed")
            await self._tracker.add_comment(
                repo, str(issue_number),
                f"Failed to create implementation plan: {e}",
            )
            return []

        # Create sub-issues
        created_issues = []
        for i, task in enumerate(plan.get("sub_tasks", [])):
            has_deps = bool(task.get("depends_on"))

            ac_list = "\n".join(f"- [ ] {ac}" for ac in task.get("acceptance_criteria", []))
            files_list = "\n".join(f"- `{f}`" for f in task.get("estimated_files", []))

            sub_body = f"""## Parent Issue
Part of #{issue_number}

## Task
{task.get('description', '')}

## Acceptance Criteria
{ac_list}

## Files Likely Affected
{files_list}

---
_Auto-generated by Tech Lead Agent from #{issue_number}_"""

            labels = ["sub-issue"]
            if has_deps:
                labels.append("ai-waiting")

            sub_issue = await self._tracker.create_subissue(
                repo=repo,
                parent_id=str(issue_number),
                title=f"[Sub #{issue_number}] {task['title']}",
                body=sub_body,
                labels=labels,
            )
            created_issues.append({"number": sub_issue.number, "title": task["title"]})
            logger.info(f"Created sub-issue #{sub_issue.number}: {task['title']}")

        # Update parent issue with plan summary
        plan_comment = f"""## Implementation Plan

{plan.get('plan_summary', '')}

### Sub-tasks
{chr(10).join(f"- #{ci['number']}: {ci['title']}" for ci in created_issues)}

### Risks
{chr(10).join(f"- {r}" for r in plan.get('risks', []))}"""

        plan_comment = embed_metadata(plan_comment, {
            "type": "plan",
            "parent_issue": issue_number,
            "sub_issues": [ci["number"] for ci in created_issues],
        })

        await self._tracker.add_comment(repo, str(issue_number), plan_comment)

        # Label parent as epic
        await self._labels.add_label(repo, str(issue_number), "epic")
        await self._labels.remove_label(repo, str(issue_number), "ai-planning")

        return created_issues


_planner: Planner | None = None


def get_planner() -> Planner:
    global _planner
    if _planner is None:
        _planner = Planner()
    return _planner
